# # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # #
# Airtheon's Essentials plugin  #
# # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # #

### Spawn command ###############

# If the /spawn command doesn't send you to the right main world.
# uncomment this command and replace "world" with the name of the world you want to use as the main world.
# main-world: 'world'

# If you don't want to use a main world and just teleport to the dimension's spawn instead, set this to true.
use-main: true

#################################

### Sleep checker ###############
# Set this to false if you want to disable sleep checker and use vanilla sleep settings.
use-sleep-checker: true

# Make this false if you want one player to always be enough to sleep through the night.
use-percentile-sleep: true

# When use-percentile-sleep is enabled, this is the percentage of players in the world that must sleep,
# before it becomes day again.
sleep-percentile: 33

#################################